#! /bin/bash

#Colors
WARN="%{B#b71c1c}"

#Universal
clock() {
	DATE=$(date "+%a %d %b, %T")
	echo -n "${DATE,,}"
}

colortemp() {
	TEMP=$(redshift -p | grep K | awk '{print $3}')
	echo -en "\uf0eb $TEMP"
}

desktop() {
	DESKS=$(bspc query -D -d focused)
	echo -en "\uf108 $DESKS"
}

#Laptop-specific
battery() {
	BAT=$(acpi -b | awk '{print $4}' | sed 's/%.*//g')
	CHARGING=$(cat /sys/class/power_supply/AC/online)
	if (( $CHARGING == 1 )); then
		ICON="\uf1e6"
	else
		case "$BAT" in
			[0-9]|1[0-9])
				ICON="\uf244";;
			[2-3][0-9])
				ICON="\uf243";;
			[4-5][0-9])
				ICON="\uf242";;
			[6-7][0-9])
				ICON="\uf241";;
			[8-9][0-9]|100)
				ICON="\uf240";;
		esac
	fi
	(( $BAT <= 10 )) && echo -en "$WARN$ICON $BAT%%{B-}" || echo -en "$ICON $BAT%"
}

volume() {
	[[ $(pamixer --get-mute) == "true" ]]  && echo -en "\uf026 mute" || echo -en "\uf028 $(pamixer --get-volume)%"
}

brightness() {
	BRIGHT=$(xbacklight | awk '{printf("%1.f\n", $1)}')
	echo -en "\uf185 $BRIGHT%"
}

ssid() {
	SSID=$(iwgetid -r)
	(( $? == 0 )) && echo -en "\uf1eb $SSID" || echo -en "$WARN\uf1eb off%{B-}"
}

#Run
if [[ $HOSTNAME == "MacPherson" || $HOSTNAME == "Paradisio" ]]; then
	while true; do
		echo "%{l} $(desktop) | $(colortemp) | $(brightness)%{c}$(clock)%{r}$(ssid) | $(volume) | $(battery) "
		sleep 0.05
	done
elif [[ $HOSTNAME == "Xanadu" ]]; then
	while true; do
		echo "%{l} $(desktop) | $(colortemp)%{c}$(clock) "
		sleep 0.05
	done
else
	echo "Invalid host"
fi
