
[env]
TERM = "xterm-256color"

[window]
padding = { x = 18, y = 18 }
# decorations = "Transparent"
option_as_alt = "Both"

[scrolling]
history = 100000

[font]
normal = { family = "M+1Code Nerd Font", style = "Regular" }
size = 18

[keyboard]
bindings = [
	{ key = "Tab", mods = "Control", action = "SelectNextTab" },
	{ key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]
