#!/usr/bin/env sh
set -eu
export PATH="$(dirname $(realpath $0))/lib:$PATH"

if [ "$(platform)" = "macOS" ]; then
	if ! has_cmd brew; then
		echo "Installing brew..."
		bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		eval "$(/opt/homebrew/bin/brew shellenv)"
		assert_has_cmd brew
	fi
fi

for pkg in $(list_pkgs); do
	if ! is_pkg_installed "$pkg"; then
		echo "Installing $pkg..."
		install_pkg "$pkg"
	fi
done

if [ "$(platform)" = "macOS" ]; then
	for cask in $(list_casks); do
		if ! is_pkg_installed --cask "$pkg"; then
			echo "Installing $pkg..."
			install_pkg --cask "$pkg"
		fi
	done
fi

if [ "$(platform)" = "macOS" ]; then
	export FISH_PATH="/opt/homebrew/bin/fish"
elif [ "$(platform)" = "linux_with_nix" ]; then
	export FISH_PATH="/usr/bin/fish"
fi

if ! grep "^$FISH_PATH\$" /etc/shells > /dev/null; then
	echo "Adding $FISH_PATH to /etc/shells..."
	echo "$FISH_PATH" | sudo tee -a /etc/shells > /dev/null
fi

if [ "$(get_login_shell)" != "$FISH_PATH" ]; then
	echo "Setting $FISH_PATH as the login shell for $USER..."
	chsh -s "$FISH_PATH"
fi

if [ "$(platform)" = "macOS" ] && [ "$(get_login_shell root)" != "$FISH_PATH" ]; then
	echo "Setting $FISH_PATH as the login shell for root..."
	sudo chsh -s "$FISH_PATH"
fi

if [ "$(platform)" = "macOS" ]; then
	export PATH="/opt/homebrew/bin:$PATH"
elif [ "$(platform)" = "linux_with_nix" ]; then
	export PATH="$HOME/.nix-profile/bin:$PATH"
fi

export PATH="$HOME/.local/bin:$PATH"

assert_has_cmd stow
for module in $(list_modules); do
	echo "Stowing $module..."
	stow --no-folding -t ~ $module
done

assert_has_cmd peru
peru --file peru.yaml --sync-dir "$HOME" sync

assert_has_cmd bat
bat cache --build

assert_has_cmd asdf
for lang in deno nodejs python rust; do
	if ! asdf plugin list | grep "^$lang\$" > /dev/null; then
		echo "Adding $lang with asdf..."
		asdf plugin add "$lang"
		asdf install "$lang" latest
		asdf global "$lang" latest
	fi
done
