[admiral]
items = ["left",
					"delimeter", "workspace",
				"right",
					"clock", "delimeter",
					"net", "delimeter",
					"redshift", "delimeter",
					"volume", "delimeter",
					"brightness", "delimeter",
					"battery", "delimeter"
				]

[workspace]
path = "./workspace"

[volume]
path = "./vol"
reload = 0.1

[brightness]
path = "./brightness"
reload = 0.1

[clock]
path = "./clock"

[net]
path = "./net"
reload = 1

[redshift]
path = "./redshift"
reload = 1

[battery]
path = "./battery"
reload = 1

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[delimeter]
path = "echo '  '"
static = true
