#!/usr/bin/env sh

EXISTING_CONFIG="$(cat)"

CODER_CONFIG="$(echo "$EXISTING_CONFIG" | sed -n '/# ------------START-CODER-----------/,/# ------------END-CODER------------/p')"

cat << EOF
Host *
	IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

Host github.com
	Hostname ssh.github.com
EOF

if [ -n "$CODER_CONFIG" ]; then
	echo "\n$CODER_CONFIG"
fi
