#!/usr/bin/env sh

EXISTING_CONFIG="$(cat)"

CODER_CONFIG="$(echo "$EXISTING_CONFIG" | sed -n '/# ------------START-CODER-----------/,/# ------------END-CODER------------/p')"

cat << EOF
Host github.com
	Hostname ssh.github.com
EOF

if [ "$(chezmoi execute-template '{{ .chezmoi.os }}')" = "darwin" ]; then
	cat << EOF

Host *
	IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

Host sheoldred
	Hostname 192.168.1.99
	ForwardAgent yes
EOF
fi

if [ -n "$CODER_CONFIG" ]; then
	echo "\n$CODER_CONFIG"
fi
