#!/usr/bin/env bash

source screen_vars

while read -r line; do
	echo -n "%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}"
	case $line in
		W*)
			IFS=':'
			set -- ${line#?}
			desks=""
			while [ $# -gt 0 ]; do
				item="$1"
				name="${item#?}"
				desk="$(echo $item | sed 's/[ofuOFU]//g')"
				case $item in
					[ou]*)
						# unfocused occupied or urgent desktop
						desks="$desks %{A:bspc desktop -f $name:}"
						desks="$desks $desk "
						desks="$desks%{A}"
						;;
					[OFU]*)
						# focused desktop
						desks="$desks %{A:bspc desktop -f $name:}"
						desks="$desks%{B$FG}%{F$BG} $desk %{B$BG}%{F$FG}"
						desks="$desks%{A}"
						;;
				esac
				shift
			done
	esac
	desks=$(echo -n "$desks" | sed 's/ //')
	echo -n "$desks"
	echo "%{A}%{A}"
done < <(bspc subscribe report)
