#!/bin/sh

. $HOME/.config/admiral.d/config

# Panel 
PW=170
PH=62
PX=760
PY=55


# n30f -d -x 755 -y 40 $HOME/.config/admiral.d/popups/power/bg.png &


echo " %{F$RED}%{F-} %{A:s:}Shutdown%{A} %{F$GREEN} %{F-}%{A:l:}Lock%{A} %{F$BLUE} %{F-}%{A:e:}Exit%{A}" | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$FONT2" -B "$BBLACK" -F "$FG" -dp | \
    while :; do
        read line
        case $line in 
            'e')
                p=$(pgrep -n lemonbar)
                n=$(pgrep -n n30f)
                kill $n
                kill $p 
                exit 
                ;;
            'l')
                i3lock-fancy &
                p=$(pgrep -n lemonbar)
                n=$(pgrep -n n30f)
                kill $n
                kill $p 
                exit                
                ;;
            's')
                sudo /sbin/shutdown -h now
                exit
                ;;
        esac
    done
