[admiral]
items = ["center",
					"workspace", "delimeter",
					"volume", "delimeter",
					"clock", "delimeter",
					"net", "delimeter",
					"battery",
				]

[volume]
path = "./vol"
reload = 0.1

[net]
path = "./net"
reload = 20

[ram]
path = "./ram"
reload = 0.1

[battery]
path = "./battery"
reload = 10

[clock]
path = "./clock"
reload = 1

[workspace]
path = "./workspace"

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[delimeter]
path = "echo '  '"
static = true
