#!/usr/bin/env bash

source screen_vars

if [[ -d /sys/class/power_supply/BAT0 ]]; then

        batteryState=$(cat /sys/class/power_supply/BAT0/status)
        batteryPower=$(cat /sys/class/power_supply/BAT0/capacity)

        # Determine battery icon based on capacity and state.
        if [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 20 ]]; then
            batteryIcon=""
            batteryColor=${WARN}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 40 ]]; then
            batteryIcon=""
            batteryColor=${FG}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 60 ]]; then
            batteryIcon=""
            batteryColor=${FG}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 80 ]]; then
            batteryIcon=""
            batteryColor=${FG}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 100 ]]; then
            batteryIcon=""
            batteryColor=${FG}
        else
            batteryIcon=""
            batteryColor=${FG}
        fi
        echo "%{F$batteryColor}${batteryIcon} %{F$FG}${batteryPower}%"
    else
        echo "%{F$WARN}No Battery Detected"
fi	
