#!/bin/bash
#
# mohabaks, 23 Aug 2016 22)
# https)
# Lemonbar Configs
#

# Panel 
PW=480
PH=24
PX=450
PY=12

# Fetch the Colors
BG=$(xrq background)
FG=$(xrq foreground)

BLACK=$(xrq color0)
BBLACK=$(xrq color8)

RED=$(xrq color1)
BRED=$(xrq color9)

GREEN=$(xrq color2)
BGREEN=$(xrq color10)

YELLOW=$(xrq color3)
BYELLOW=$(xrq color11)

BLUE=$(xrq color4)
BBLUE=$(xrq color12)

MAGENTA=$(xrq color5)
BMAGENTA=$(xrq color13)

CYAN=$(xrq color6)
BCYAN=$(xrq color14)

WHITE=$(xrq color7)
BWHITE=$(xrq color15)
