#!/usr/bin/env bash

source screen_vars
networkIcon=""

if ping -W 3 -c 3 8.8.8.8 >> /dev/null 2>&1; then
	NAME=$(iwgetid -r 2> /dev/null)
	if (( $? == 0 )); then
		echo "${networkIcon} $NAME"
	else
		echo "${networkIcon} Online"
	fi
else
	echo "%{B$FG}%{F$BG}${networkIcon} Offline%{B$BG}%{F$FG}"
fi
