#!/usr/bin/env bash

source screen_vars

_volumeState=$(pamixer --get-volume)
volumeState="$(printf %02d $_volumeState)"
volumeIcon=""

if [[ $(pamixer --get-mute) == 'true' ]]; then
	volumeColor=$SELBG
	echo "${volumeIcon} %{F$SELBG}00%{F$FG}"
else
	echo "${volumeIcon} ${volumeState}"
fi
