#!/usr/bin/env bash

while read -r line; do
	echo -n "%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}"
	case $line in
		W*)
			IFS=':'
			set -- ${line#?}
			desks=""
			while [ $# -gt 0 ]; do
				item="$1"
				name="${item#?}"
				case $item in
					[ou]*)
						# occupied urgent unfocused desktop
						desks="$desks %{A:bspc desktop -f $name:}"
						desks="$desks"
						desks="$desks%{A}"
						;;
					[OFU]*)
						# focused desktop
						desks="$desks %{A:bspc desktop -f $name:}"
						desks="$desks"
						desks="$desks%{A}"
						;;
				esac
				shift
			done
	esac
	desks = $(echo -n "$desks" | sed 's/ //')
	echo -n "$desks"
	echo "%{A}%{A}"
done < <(bspc subscribe report)
