#!/usr/bin/env bash

while read -r line; do
	echo -n "%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}"
	case $line in
		W*)
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ]; do
				item="$1"
				name="${item#?}"
				case $item in
					[ofu]*)
						# free desktop
						echo -n "%{A:bspc desktop -f $name:}"
						echo -n ""
						echo -n "%{A} "
						;;
					[OFU]*)
						# focused free desktop
						echo -n "%{A:bspc desktop -f $name:}"
						echo -n ""
						echo -n "%{A} "
						;;
				esac
				shift
			done
	esac
	echo "%{A}%{A}"
done < <(bspc subscribe report)
