#! /bin/bash

source ~/dotfiles/scripts/screen_vars

# configure borders, gaps
bspc config border_width $BORDER_WIDTH
bspc config window_gap $GAPS
bspc config split_ratio 0.5

# focusing
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config ignore_ewmh_focus true

bspc config presel_feedback_color $BG
bspc config normal_border_color $(xrq color10)
bspc config focused_border_color $(xrq color14)

# set workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# don't blind me
xbacklight -set 50

# disable coasting
synclient CoastingSpeed=0

# enable two-finger horizontal scrolling
synclient HorizTwoFingerScroll=1

nice admiral | bar bottom | sh
