#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# themes!
xrdb ~/.Xresources
xrdb -merge ~/.colors/xresources/gruvbox-dark.xresources
source ~/.bash_aliases; setbg &

# hidpi
if [[ $HOSTNAME == "alpamayo" ]]; then
	echo "Xft.dpi: 144" | xrdb -merge
	echo "barHeight: 48" | xrdb -merge
else
	echo "Xft.dpi: 96" | xrdb -merge
	echo "barHeight: 36" | xrdb -merge
fi

# don't use that stupid cross pointer
xsetroot -cursor_name left_ptr &

# no bell
xset -b &

# disable auto screensaver
xset s off -dpms &

# configure borders, gaps
bspc config bottom_padding 48 # temporary
bspc config border_width 0
bspc config window_gap 18
bspc config split_ratio 0.5

# preselection color
bspc config presel_feedback_color "#ebdbb2"

# focusing
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

# set workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# zathura, libreoffice start floating for some reason
bspc rule -a Zathura state=tiled
bspc rule -a *:libreoffice state=tiled

# autostart apps
run_keybase &
thunar --daemon &
polybar main &

################################################################################
### laptop specific stuff
################################################################################
if [[ $HOSTNAME == "alpamayo" || $HOSTNAME == "eiger" ]]; then
	# no hissing noises
	amixer -c PCH cset 'name=Headphone Mic Boost Volume' 1

	# networkmanager
	nm-applet &

	# don't blind me
	xbacklight -set 50 &
fi
