#! /usr/bin/env bash

# themes!
xrdb ~/.Xresources
xrdb -merge ~/.colors/nord
feh --no-fehbg --bg-fill ~/.wallpaper &

# hidpi
if [[ $HOST == "alpamayo" ]]; then
  echo "Xft.dpi: 144" | xrdb -merge
  echo "barHeight: 48" | xrdb -merge
else
  echo "Xft.dpi: 96" | xrdb -merge
  echo "barHeight: 36" | xrdb -merge
fi

# make caps be escape
setxkbmap -option caps:escape &

# don't use that stupid cross pointer
xsetroot -cursor_name left_ptr &

# no bell
xset -b &

# disable auto screensaver
xset s off -dpms &

# no mouse acceleration
xset m 0 0

# key repeat rate
xset r rate 250

# configure borders, gaps
bspc config bottom_padding $(xrq barHeight)
bspc config border_width 4
bspc config window_gap 18
bspc config split_ratio 0.5

# preselection color
bspc config presel_feedback_color "#ebdbb2"

# focusing
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

# set workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# libreoffice starts floating for some reason
bspc rule -a *:libreoffice state=tiled
bspc rule -a Zathura state=tiled

# autostart apps
notify-osd &
polybar main &
nm-applet &
dropbox &
redshift &
run_keybase &

# laptop specific stuff
if [[ $HOST == "alpamayo" ]]; then
  # no hissing noises
  amixer -c PCH cset 'name=Headphone Mic Boost Volume' 1

  # don't blind me
  xbacklight -set 50 &
fi

# start pulseaudio
pulseaudio --start &

# start sxhkd
sxhkd &
