[admiral]
items = ["center",
					"workspace", "delimeter",
					"clock", "delimeter",
					"redshift", "delimeter",
					"net"
				]

[workspace]
path = "./workspace"

[clock]
path = "./clock"
reload = 1

[redshift]
path = "./redshift"
reload = 1

[net]
path = "./net"
reload = 20

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[delimeter]
path = "echo '  '"
static = true
