[admiral]
items = ["left",
					"delimeter", "workspace",
				"center",
					"clock", "delimeter",
				"right",
					"net", "delimeter",
					"redshift", "delimeter"
				]

[workspace]
path = "./workspace"

[clock]
path = "./clock"

[net]
path = "./net"
reload = 1

[redshift]
path = "./redshift"
reload = 1

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[delimeter]
path = "echo '  '"
static = true
