return {
	"ibhagwan/fzf-lua",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	opts = {
		colorschemes = {
			ignore_patterns = {
				"^blue$",
				"^darkblue$",
				"^default$",
				"^delek$",
				"^desert$",
				"^elflord$",
				"^evening$",
				"^habamax$",
				"^industry$",
				"^koehler$",
				"^lunaperche$",
				"^morning$",
				"^murphy$",
				"^pablo$",
				"^peachpuff$",
				"^quiet$",
				"^retrobox$",
				"^ron$",
				"^shine$",
				"^slate$",
				"^sorbet$",
				"^torte$",
				"^vim$",
				"^wildcharm$",
				"^zaibatsu$",
				"^zellner$",
			},
		},
		files = {
			fd_opts = "--color=never --type f --hidden --exclude .git",
		},
		lsp = {
			finder = {
				includeDeclaration = false,
			},
		},
		winopts = {
			preview = {
				vertical = "down:40%",
				horizontal = "right:40%",
				flip_columns = 192,
			},
		},
	},
	cmd = "FzfLua",
	keys = {
		{ [[<Leader>\]], [[<cmd>FzfLua lsp_definitions<cr>]] },
		{ [[<Leader>']], [[<cmd>FzfLua lsp_references<cr>]] },
		{ [[<Leader>"]], [[<cmd>FzfLua lsp_incoming_calls<cr>]] },
		{ [[<C-p>]], [[<cmd>FzfLua files<cr>]] },
		{ [[<C-b>]], [[<cmd>FzfLua buffers<cr>]] },
		{ [[<C-g>]], [[<cmd>FzfLua live_grep_native<cr>]] },
		{ [[<C-k>]], [[<cmd>FzfLua<cr>]] },
	},
}
