#! /bin/bash

bspc config border_width 6
bspc config window_gap $(xrq barOffset)
bspc config top_padding $(( $(xrq barHeight) + $(xrq barOffset) ))
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config normal_border_color $(xrq accent)
bspc config focused_border_color $(xrq color1)

xrandr --listactivemonitors | grep -v eDP1 | grep DP1
if (( $? == 0 )); then
	~/.screenlayout/keybase.sh
	bspc monitor eDP1 -d aux
	bspc monitor DP1 -d 1 2 3 4 5 6 7 8 9 0
	setbg
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi
