#! /bin/bash

bspc config border_width 6
bspc config window_gap $(xrq barYOffset)
bspc config top_padding 0
bspc config split_ratio 0.25
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config normal_border_color $(xrq color10)
bspc config focused_border_color $(xrq color14)

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
xbacklight -set 50
