#! /bin/bash

bspc config border_width 6
bspc config window_gap $(xrq barOffset)
bspc config top_padding $(( $(xrq barHeight) + $(xrq barOffset) ))
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config ignore_ewmh_focus true

bspc config normal_border_color $(xrq color7)
bspc config focused_border_color $(xrq color5)

xrandr -q  | grep -e '\<DP1\> \<connected\>'
if (( $? == 0 )); then
	~/.screenlayout/keybase.sh
	bspc monitor eDP1 -d 0
	bspc monitor DP1 -d 1 2 3 4 5
	source ~/.bash_aliases; setbg
	xbacklight -set 100
	~/dotfiles/scripts/bar
else
	~/.screenlayout/normal.sh
	bspc monitor -d 1 2 3 4 5 0
	source ~/.bash_aliases; setbg
	xbacklight -set 50
	~/dotfiles/scripts/bar
fi
