#!/usr/bin/env sh
set -eu
export PATH="$(dirname $(realpath $0)):$PATH"

export USERNAME="${1:-$USER}"

if [ "$(platform)" = "macOS" ]; then
	dscacheutil -q user -a name "$USERNAME" | grep "^shell:" | sed 's/^shell: //'
elif [ "$(platform)" = "linux_with_nix" ]; then
	getent passwd "$USERNAME" | cut -d ":" -f 7
fi
