#!/usr/bin/env sh
set -eu
export PATH="$(dirname $(realpath $0)):$PATH"

if [ "$(platform)" = "macOS" ]; then
	assert_has_cmd brew
	brew install "$1"
elif [ "$(platform)" = "coder" ]; then
	assert_has_cmd nix
	if ! nix registry list | grep -q unstable 2>/dev/null; then
		nix registry add nixpkgs-unstable github:NixOS/nixpkgs/nixpkgs-unstable
	fi
	nix profile install "nixpkgs-unstable#$1"
else
	echo "Cannot install $1 without a package manager!"
	exit 1
fi
