#!/usr/bin/env sh
set -eu
export PATH="$(dirname $(realpath $0)):$PATH"

echo atuin
echo bandwhich
echo bat
echo bottom
echo eza
echo fd
echo fish
echo fzf
echo gh
echo gist
if [ "$(platform)" = "macOS" ]; then
	echo git-delta
elif [ "$(platform)" = "linux_with_nix" ]; then
	echo delta
fi
echo htop
echo hwatch
echo jq
echo magic-wormhole
echo mise
echo neofetch
echo neovim
echo nmap
echo ouch
echo pastel
echo peru
if [ "$(platform)" = "macOS" ]; then
	echo pidof
fi
echo ripgrep
echo rlwrap
echo rnr
echo rsync
echo sd
echo starship
echo stow
echo tealdeer
if [ "$(platform)" = "macOS" ]; then
	echo telnet
fi
echo tmux
echo watchexec
echo wget
echo xh
echo zoxide
