#!/usr/bin/env sh
set -eu
export PATH="$(dirname $(realpath $0)):$PATH"

echo asdf
echo atuin
echo fish
if [ $(platform) = "macOS" ]; then
	echo ghostty
fi
echo git
echo nvim
if [ $(platform) = "macOS" ]; then
	echo ssh
fi
echo starship
echo tmux
