#!/usr/bin/env sh
set -eu
export PATH="$(dirname $(realpath $0)):$PATH"

cat << EOF
1password
alfred
alt-tab
appcleaner
audio-hijack
chirp
chromium
discord
fantastical
firefox
fission
font-caskaydia-cove-nerd-font
font-fira-code-nerd-font
font-ia-writer-quattro
font-iosevka-nerd-font
font-m+-nerd-font
font-mononoki-nerd-font
garmin-express
ghostty
iina
insta360-studio
jordanbaird-ice
keyboard-maestro
linearmouse
logitech-g-hub
loopback
metaimage
monitorcontrol
moom
mullvadvpn
obsidian
powerphotos
rocket
signal
soulver
soulver-cli
soundsource
spotify
via
visual-studio-code
wireshark
zen-browser
zoom
EOF
