#!/usr/bin/env sh
set -eu
export PATH="$(dirname $(realpath $0)):$PATH"

if [ "$(uname -om)" = "Darwin arm64" ]; then
	echo "macOS"
elif [ "$(uname -om)" = "x86_64 GNU/Linux" ] && has_cmd nix; then
	echo "linux_with_nix"
fi
