##################
# catppuccin-latte
##################
# [colors]
# table_header_color = "#dc8a78"
# all_cpu_color = "#dc8a78"
# avg_cpu_color = "#e64553"
# cpu_core_colors = ["#d20f39","#fe640b","#df8e1d","#40a02b","#209fb5","#8839ef"]
# ram_color = "#40a02b"
# swap_color = "#fe640b"
# rx_color = "#40a02b"
# tx_color = "#d20f39"
# widget_title_color = "#dd7878"
# border_color = "#acb0be"
# highlighted_border_color = "#ea76cb"
# text_color = "#4c4f69"
# graph_color = "#6c6f85"
# cursor_color = "#ea76cb"
# selected_text_color = "#dce0e8"
# selected_bg_color = "#8839ef"
# high_battery_color = "#40a02b"
# medium_battery_color = "#df8e1d"
# low_battery_color = "#d20f39"
# gpu_core_colors = ["#209fb5","#8839ef","#d20f39","#fe640b","#df8e1d","#40a02b"]
# arc_color = "#04a5e5"

###################
# catppuccin-frappe
###################
# [colors]
# table_header_color = "#f2d5cf"
# all_cpu_color = "#f2d5cf"
# avg_cpu_color = "#ea999c"
# cpu_core_colors = ["#e78284","#ef9f76","#e5c890","#a6d189","#85c1dc","#ca9ee6"]
# ram_color = "#a6d189"
# swap_color = "#ef9f76"
# rx_color = "#a6d189"
# tx_color = "#e78284"
# widget_title_color = "#eebebe"
# border_color = "#626880"
# highlighted_border_color = "#f4b8e4"
# text_color = "#c6d0f5"
# graph_color = "#a5adce"
# cursor_color = "#f4b8e4"
# selected_text_color = "#232634"
# selected_bg_color = "#ca9ee6"
# high_battery_color = "#a6d189"
# medium_battery_color = "#e5c890"
# low_battery_color = "#e78284"
# gpu_core_colors = ["#85c1dc","#ca9ee6","#e78284","#ef9f76","#e5c890","#a6d189"]
# arc_color = "#99d1db"

######################
# catppuccin-macchiato
######################
# [colors]
# table_header_color = "#f4dbd6"
# all_cpu_color = "#f4dbd6"
# avg_cpu_color = "#ee99a0"
# cpu_core_colors = ["#ed8796","#f5a97f","#eed49f","#a6da95","#7dc4e4","#c6a0f6"]
# ram_color = "#a6da95"
# swap_color = "#f5a97f"
# rx_color = "#a6da95"
# tx_color = "#ed8796"
# widget_title_color = "#f0c6c6"
# border_color = "#5b6078"
# highlighted_border_color = "#f5bde6"
# text_color = "#cad3f5"
# graph_color = "#a5adcb"
# cursor_color = "#f5bde6"
# selected_text_color = "#181926"
# selected_bg_color = "#c6a0f6"
# high_battery_color = "#a6da95"
# medium_battery_color = "#eed49f"
# low_battery_color = "#ed8796"
# gpu_core_colors = ["#7dc4e4","#c6a0f6","#ed8796","#f5a97f","#eed49f","#a6da95"]
# arc_color = "#91d7e3"

##################
# catppuccin-mocha
##################
[colors]
table_header_color = "#f5e0dc"
all_cpu_color = "#f5e0dc"
avg_cpu_color = "#eba0ac"
cpu_core_colors = ["#f38ba8","#fab387","#f9e2af","#a6e3a1","#74c7ec","#cba6f7"]
ram_color = "#a6e3a1"
swap_color = "#fab387"
rx_color = "#a6e3a1"
tx_color = "#f38ba8"
widget_title_color = "#f2cdcd"
border_color = "#585b70"
highlighted_border_color = "#f5c2e7"
text_color = "#cdd6f4"
graph_color = "#a6adc8"
cursor_color = "#f5c2e7"
selected_text_color = "#11111b"
selected_bg_color = "#cba6f7"
high_battery_color = "#a6e3a1"
medium_battery_color = "#f9e2af"
low_battery_color = "#f38ba8"
gpu_core_colors = ["#74c7ec","#cba6f7","#f38ba8","#fab387","#f9e2af","#a6e3a1"]
arc_color = "#89dceb"
