#! /usr/bin/env bash

function count_down() {
	mins=$1
	while (( $mins >= 0 )); do
		export CD_5217_TIME="$mins"
		mins=$(( $mins - 1 ))
		sleep 60
	done
}

while true; do
	export CD_5217="work:"
	count_down 52
	export CD_5217="rest:"
	count_down 17
done

unset CD_5217_TIME
unset CD_5217
