#!/usr/bin/env bash

USAGE="Usage: backlightctl [up|down|query]"

if [[ $# != 1 ]]; then
	echo "$USAGE"
elif [[ $1 == "up" ]]; then
	xbacklight -set $(( $(xbacklight | awk '{printf("%1.f\n", $1)}') + 5 )) -time 0 -steps 1
elif [[ $1 == "down" ]]; then
	xbacklight -set $(( $(xbacklight | awk '{printf("%1.f\n", $1)}') - 5 )) -time 0 -steps 1
elif [[ $1 == "query" ]]; then
	xbacklight | awk '{printf("%1.f\n", $1)}'
else
	echo "$USAGE"
fi
