#!/usr/bin/env bash

USAGE="Usage: backlightctl [up|down|set|query]"

if [[ $1 == "up" && $# == 1 ]]; then
	xbacklight -set $(( $(xbacklight | awk '{printf("%1.f\n", $1)}') + 5 )) -time 0 -steps 1
elif [[ $1 == "down" && $# == 1 ]]; then
	xbacklight -set $(( $(xbacklight | awk '{printf("%1.f\n", $1)}') - 5 )) -time 0 -steps 1
elif [[ $1 == "set" && $# == 2 ]]; then
	xbacklight -set "$2"
elif [[ $1 == "query" && $# == 1 ]]; then
	xbacklight | awk '{printf("%1.f\n", $1)}'
else
	echo "$USAGE"
fi
