#!/bin/bash

BG="$(xrq background)"
FG="$(xrq foreground)"
WIDTH="$(( $(xdpyinfo | awk '/dimensions:/ {print $2; exit}' | cut -dx -f1)-$(( 2*$(xrq barOffset) )) ))"
HEIGHT="$(xrq barHeight)"
XOFF="$(xrq barOffset)"
YOFF=$XOFF
FONT=$(xrq barFont | cut -d: -f2,3)
ICONS="$(xrq iconFont | sed 's/.*xft://g')"

pgrep lemonbar &> /dev/null
if (( $? == 0 )); then
	killall lemonbar
fi

if [[ $HOSTNAME == "annapurna" || $HOSTNAME == "longs" || $HOSTNAME == "eiger" ]]; then
	nice ~/.config/lemonbar/lemonbar | lemonbar -B $BG -F $FG -g $WIDTH\x$HEIGHT\+$XOFF\+$YOFF -o 1 -f $FONT -o -3 -f $ICONS & disown
else
	echo "Need to configure lemonbar for new hostname"
fi
