#!/usr/bin/env bash

source screen_vars
USAGE="Usage: bar [top|bottom]"
BOTTOM=""

if [[ $# != 1 ]]; then
	echo "$USAGE"
	exit
elif [[ $1 == "top" ]]; then
	bspc config bottom_padding 0
	bspc config top_padding $BAR_HEIGHT+$GAPS
elif [[ $1 == "bottom" ]]; then
	bspc config top_padding 0
	bspc config bottom_padding $BAR_HEIGHT+$GAPS
	BOTTOM="-b"
else
	echo "$USAGE"
	exit
fi

nice admiral | nice lemonbar -B $BG -F $FG -g $BAR_WIDTH\x$BAR_HEIGHT\+$XOFF\+$YOFF -f $FONT -o 0 -f $ICONS -o -3 $BOTTOM | sh
