#!/usr/bin/env bash

PADDING=$(( $(xrq barHeight) + $(xrq barYOffset) ))
USAGE="Usage: barctl [peek|toggle]"

function show() {
	nice admiral | bar top | sh & disown
}

function hide() {
	killall admiral
}

function peek() {
	show
	sleep 3
	hide
}

if [[ $# != 1 ]]; then
	echo $USAGE
elif [[ $1 == "peek" ]]; then
	if pgrep "admiral" > /dev/null; then
		exit
	else
		peek
	fi
elif [[ $1 == "toggle" ]]; then
	if pgrep "admiral" > /dev/null; then
		hide
		bspc config top_padding 0
	else
		bspc config top_padding $PADDING
		show
	fi
else
	echo $USAGE
fi
