#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

USAGE="Usage: hidpi [command] [args]"

if [[ $# == 0 ]]; then
  echo $USAGE
  exit
fi

COMMAND=$1
shift
ARGS=$*

if [[ $HOSTNAME == "alpamayo" ]]; then
	$COMMAND --force-device-scale-factor=1.65 "$ARGS"
elif [[ $HOSTNAME == "eiger" ]]; then
	$COMMAND --force-device-scale-factor=1.25 "$ARGS"
else
	$COMMAND --force-device-scale-factor=1.0 "$ARGS"
fi
