#!/usr/bin/env bash

if [[ $HOSTNAME == "huascaran" ]]; then
	$1 --force-device-scale-factor=1.5
elif [[ $HOSTNAME == "eiger" ]]; then
	$1 --force-device-scale-factor=1.25
else
	$1 --force-device-scale-factor=1.0
fi
