#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

TMP_BG=/tmp/screen.png
ICON=~/dotfiles/scripts/rmlock.png

maim $TMP_BG
convert $TMP_BG -scale 10% -scale 1000% -fill black -colorize 50% $TMP_BG
convert $TMP_BG $ICON -gravity center -composite -matte $TMP_BG

i3lock -i $TMP_BG
