#!/usr/bin/env python

import os, sys, re, random

base_dir = os.getenv("HOME") + "/media"
show = ""

if len(sys.argv) == 2:
    show = sys.argv[1]

# select archer or ricknmorty
while show not in ["archer", "ricknmorty"]:
    show = random.choice(os.listdir(base_dir))

# select an episode
show_dir = base_dir + "/" + show
season = random.choice(os.listdir(show_dir))
season_dir = show_dir + "/" + season
episode = random.choice(os.listdir(season_dir))
episode_path = season_dir + "/" + episode

# notify
if show is "ricknmorty":
    show_clean = "rick and morty"
else:
    show_clean = show

episode_clean = re.sub(r'_', " ", re.sub(r'\..*', "", episode))

os.system("notify-send 'Playing " + show.title() + ", " + season.title() + episode_clean + "'")

# play
os.system("mpv " + episode_path)
