#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

BG="$(xrq background)"
FG="$(xrq foreground)"
SELBG="$(xrq color1)"
WARN="$SELBG"
SCREEN_WIDTH="$(xdpyinfo | awk '/dimensions:/ {print $2; exit}' | cut -dx -f1)"
SCREEN_HEIGHT="$(xdpyinfo | awk '/dimensions:/ {print $2; exit}' | cut -dx -f2)"
BAR_WIDTH="$(( $SCREEN_WIDTH-$(( 2*$(xrq barXOffset) )) ))"
BAR_HEIGHT="$(xrq barHeight)"
XOFF="$(xrq barXOffset)"
YOFF="$(xrq barYOffset)"
GAPS="$(xrq gaps)"
BORDER_WIDTH="$(( $GAPS/2 ))"
FONT="$(xrq font | cut -d: -f2,3)"
ICONS="$(xrq iconFont | sed 's/.*xft://g')"
