#!/usr/bin/env bash

BG="$(xrq color15)"
FG="$(xrq color11)"
SELBG="$(xrq color1)"
WARN="$SELBG"
SCREENWIDTH="$(xdpyinfo | awk '/dimensions:/ {print $2; exit}' | cut -dx -f1)"
SCREENHEIGHT="$(xdpyinfo | awk '/dimensions:/ {print $2; exit}' | cut -dx -f2)"
WIDTH="$(( $SCREENWIDTH-$(( 2*$(xrq barXOffset) )) ))"
HEIGHT="$(xrq barHeight)"
XOFF="$(xrq barXOffset)"
YOFF="$(xrq barYOffset)"
FONT="$(xrq font | cut -d: -f2,3)"
ICONS="$(xrq iconFont | sed 's/.*xft://g')"
