return {
	"tommcdo/vim-exchange",
	"tpope/vim-abolish",
	"tpope/vim-commentary",
	"tpope/vim-repeat",
	"tpope/vim-surround",
	"hrsh7th/nvim-cmp",
	"hrsh7th/vim-vsnip",
	"hrsh7th/cmp-nvim-lsp",
	-- "hrsh7th/cmp-vsnip",
	-- "hrsh7th/cmp-buffer",
	-- "hrsh7th/cmp-path",
	"ggandor/leap.nvim",
	-- { "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = {} },
}
