#! /usr/bin/env bash

# themes!
xrdb ~/.Xresources
feh --no-fehbg --bg-fill ~/.wallpaper &

# don't use that stupid cross pointer
xsetroot -cursor_name left_ptr

# no bell
xset -b &

# disable auto screensaver
xset s off -dpms &

# configure keyboard
xset r rate 250
setxkbmap -option caps:escape

# autostart apps
nm-applet &
dropbox &
run_keybase &
redshift -t 5500:3000 &
compton -I 0.01 -O 0.01 -D 2 &

if [[ $(hostname) = "quitaraju" || $(hostname) = "blanc" ]]; then
  # don't blind me
  xbacklight -set 50
fi
